- algs.py
adding the heap sort algorithm in reference to #8 
reference: [wikipedia](https://en.wikipedia.org/wiki/Heapsort)
> adding heapSort

- algs.py
In regards to issue:
#5 Implement a new Sorting Algorithm
> Added bogosort algorithm

- main.py
I hope I did the right pull request
> Add default values #21

- wiki.md
#27 Couldnt find a way to raise PR directly on the wiki page. I have created a .md file and raised in this PR. You can copy the content and add to Wiki. Let me know if it works out, I can add for other algorithms as well
> Added content for wiki

- main.py
I did an error check.
The program simply will not start if the data is entered incorrectly.
I need to make a pop-up window, but I think I need some help.
> Any idea, feedback or bug? #25

- algorithms/countingSort.py
> Bug in countingsort

- algorithms/bitonicSort.py
- algs.py
added bitonic sort for any length n, the problem with the other PR https://github.com/LucasPilla/Sorting-Algorithms-Visualizer/pull/37 is that it only worked for lengths that are a power of 2. (ran into the same problem at first). also had to add and import in algs.py.
> added bitonic sort

- algorithms/pancakeSort.py
- algs.py
- display.py
cool sorting algorithm, but visualisation could be better (choosing when to draw what colour, where) but okay
> added pancakesort

- algorithms/binaryinsertionSort.py
- algs.py
typical insertion sort, just uses binary search
> added binary insertion sort

- algorithms/timSort.py
- algs.py
added: algorithms/timSort.py
modified: algs.py to include timsort
Resolves #57
> Implement Tim Sort algorithm

- display.py
- main.py
#50 
- Add a new class DropdownBox for dropdown
> Change Algorithm Box to Dropdown

- display.py
#62
Use the spacebar to pause/resume the sorting algorithm
> Pause/Play Feature 

- algorithms/insertionSort.py
- display.py
- main.py
part fix for issue#20
In drawBars in display.py I added a kwargs argument, and also check for a keyword argument called 'greenRows'. This way we don't have to update each algorithm individually if we want to add these rows. I thought this would be good as that would be very time consuming, and we can change each one individually as we have time.
insertionsort.py is how you could possible implement this.
```
from display import handleDrawing
mySortedRows = []
def insertionSort(array, *args):
size = len(array)
for i in range(0, size):
j = i-1
key = array[i]
mySortedRows.append(i)        
while j >= 0 and array[j] > key:
handleDrawing(array, j, -1, i, -1, greenRows = mySortedRows)
array[j+1] = array[j]
j -= 1
array[j+1] = key
mySortedRows.clear()
```
In line 41 I added an array which …
> adding green bars and sorted array for insertionSort

- algorithms/cycleSort.py
> Fix Cycle Sort Graph

- display.py
> Fixed Delay 

- display.py
This checks if the text input is a digit before updating it, if it isn't a digit it won't update it.
Now the error check in main.py's line 55 could be deleted, as we have already checked the input, although I believe it should stay there just in case.
> Check if textbox input is a digit

- algorithms/__init__.py
- algorithms/strandSort.py
- algs.py
Strand sort implemented and everything working, please review. Thank you
> Strand sort added , working with animation

- algorithms/quickSort.py
By choosing pivot randomly, we can protect quicksort from the worst case O(n2). 
e.g. when sorted in descending order, it's the worst case for non-random pivot quicksort.
> Improve Quicksort by Adding Random Pivot

- main.py
Since greenRows is used for checking in `drawBars`, it is more performant to use a set (O(1) time complexity) than list (O(N) time complexity) in the for-loop.
> More Efficient Containment Checking

- algs.py
Algorithm labels should be more readable now.
> Revised Algorithm Names

- display.py
Summary:
- Invariants are extracted from the for-loop
- Better checking conditionals
- Tuples over lists for constant items
@LucasPilla
Please check for any error. Thanks.
> More Efficient Bar Drawing

- display.py
With a set default value for sizeBox, it becomes more independent and secure.
> More Independent Default for sizeBox

- display.py
- main.py
Now, you can adjust `delay` by scrolling your mouse (while it is hovering in the box) and also while its sorting the bars!
> Added Delay Scrolling

- display.py
> added vertical scrollbar

- algorithms/__init__.py
- algorithms/binaryinsertionSort.py
- algorithms/bitonicSort.py
- algorithms/bogoSort.py
- algorithms/bubbleSort.py
- algorithms/bucketSort.py
- algorithms/cocktailSort.py
- algorithms/combSort.py
- algorithms/countingSort.py
- algorithms/cycleSort.py
- algorithms/gnomeSort.py
- algorithms/heapSort.py
- algorithms/insertionSort.py
- algorithms/mergeSort.py
- algorithms/oddevenSort.py
- algorithms/pancakeSort.py
- algorithms/pigeonholeSort.py
- algorithms/quickSort.py
- algorithms/quickSort_LR.py
- algorithms/radixSort.py
- algorithms/selectionSort.py
- algorithms/shellSort.py
- algorithms/stoogeSort.py
- algorithms/strandSort.py
- algorithms/timSort.py
- algs.py
- display.py
- main.py
- variables.py
Sorting functions have become generators by simply replacing calls to handleDrawing by yield statements : this way their execution is still paused during the delay set by the user, the algorithm package is independent of the rest of the code, and there's only one event loop which is kept in the main function.
We use an iterator in the main function to capture the results of the yield statements, which are then used for drawing.
> turned sorting functions into generators

- algorithms/exchangeSort.py
- algs.py
> Exchange Sort Algorithm is added.

- display.py
@mugulmd
_Quick patch for #127._
Here, I've refactored the `DropdownBox` class as part of the `InputBox` class which makes consistent all boxes with labels. So now, they are easily controlled by the single `draw()` of their parent class, the `InputBox`.
> Refactored DropdownBox class

- display.py
- main.py
I put the menu on the left side instead of the bottom.
It led to some changes in the InputBox draw method and in the DropdownBox class.
Also I had to reduce a bit the size of the font to make everything fit in the window.
> Left side menu

- .markdownlint.json
- CONTRIBUTING.md
- README.md
This Project is amazing. Great Work. 
I  Made Improvement to the README.md page by adding Repo URL to clone. Improved Markdown syntax. Improved Contribution.md by adding more detail. 
Please Merge as HacktoberFest. Thank you.
> README.md & Contribution.Md

- src/algorithms/__init__.py
fix missing import issue for exchangeSort in init file
> fix exchangeSort TypeError

- src/display.py
Fixes the first half of issue #187, given the other half seemed already resolved. Simply added a condition for updating the play/pause and algorithm buttons. Couldn't do the same on the quantity box and the slider without breaking them, but this seems good to me. 
I saw @chenrbin asked to resolve this two months ago, i hope they don't mind i went ahead and gave it a try.
> Fixes issue #187

- src/display.py
- src/main.py
The execution speed can be changed using a slider. The user can either do a slide movement with its mouse to move the speed slider or simply click where he wants the slider to go. The speed range goes from 1 (slow = 1000ms delay) to 100 (fast = 10ms delay). 
Files changed :
- display.py : I've updated the already existing SlideBox
- main.py : I've added the SlideBox object and implemented the logic for the delay
> Add speed option (fixing issue #191)
